### REGISTER DOCTOR
POST http://localhost:4000/doctor/auth/register
Content-Type: application/json

{
  "email": "testing@email.com",
  "password": "doktertest",
  "name": "bambang",
  "imageURL": "abc",
  "location": "surabaya",
  "hospital": "rsud"
}

### LOGIN FOR DOCTOR
POST http://localhost:4000/doctor/auth/login
Content-Type: application/json

{
    "email": "testing@email.com",
    "password": "doktertest"
}

### GET ALL DOCTOR
GET http://localhost:4000/doctor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOTM0ZjFjMS01NDJjLTQ1OWYtYjdmMy03OGMzMjhhN2VhYTgiLCJuYW1lIjoiZG9rdGVydGVzdCIsImVtYWlsIjoidGVzdGluZzJAZW1haWwuY29tIiwicm9sZSI6ImRvY3RvciIsImlhdCI6MTY5NTY0NDM0NywiZXhwIjoxNjk1NzMwNzQ3fQ.7PAATPjERrl0TK_tgZ03oVbMl5Zu_j1wi5gATstHKYs
### GET ALL DOCTOR USING PATIENT'S TOKEN
GET http://localhost:4000/doctor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlhYWNhMDRmLWQ3ZDctNDVlMC1hYmFkLTU3YzBkMGM0ZGNjOSIsImVtYWlsIjoicGF0aWVudDFAdGVzdGluZy5jb20iLCJuYW1lIjoicGF0aWVudCB0ZXN0IiwiaW1hZ2VVUkwiOiJzdHJpbmciLCJpYXQiOjE2OTUzODYxODAsImV4cCI6MTY5NTQ3MjU4MH0.O3qEA-bK60BtroqOFYSdbYivwSg03secwa3h8U-aqIE

### FILTER DOCTOR
GET http://localhost:4000/doctor/query?location=surabaya

### EDIT DOCTOR DATA
PUT http://localhost:4000/doctor/cba93c64-9d08-4d7e-967c-ea78db18903e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmE5M2M2NC05ZDA4LTRkN2UtOTY3Yy1lYTc4ZGIxODkwM2UiLCJuYW1lIjoiYmFtYmFuZyIsImVtYWlsIjoidGVzdGluZ0BlbWFpbC5jb20iLCJyb2xlIjoiZG9jdG9yIiwiaWF0IjoxNjk1ODE3MzE3LCJleHAiOjE2OTU5MDM3MTd9.47ItkyblOp335Tfa3SgVujDYqg2DQ6hWEWlj1LWcefM
Content-Type: application/json

{
  "schedule" : [{
    "days": "senin",
    "time": ["09.00", "10.00"]
  }]
}


### CHANGE PASSWORD
PATCH http://localhost:4000/doctor/change-password/bd788478-513d-4a09-812e-f1c078f32144
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDc4ODQ3OC01MTNkLTRhMDktODEyZS1mMWMwNzhmMzIxNDQiLCJuYW1lIjoiZG9rdGVydGVzdCIsImVtYWlsIjoidGVzdGluZ0BlbWFpbC5jb20iLCJyb2xlIjoiZG9jdG9yIiwiaWF0IjoxNjk1NjUzNzMxLCJleHAiOjE2OTU3NDAxMzF9.N2IbbW65LGjfK0xR42UApjpdsMyd9pWTlwLnwmAifao
Content-Type: application/json

{
  "oldPassword": "newpassworddoctor",
  "newPassword": "doktertest"
}

### DELETE DOCTOR
DELETE http://localhost:4000/doctor/bd788478-513d-4a09-812e-f1c078f32144
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDc4ODQ3OC01MTNkLTRhMDktODEyZS1mMWMwNzhmMzIxNDQiLCJuYW1lIjoiZG9rdGVydGVzdCIsImVtYWlsIjoidGVzdGluZ0BlbWFpbC5jb20iLCJyb2xlIjoiZG9jdG9yIiwiaWF0IjoxNjk1NzMwOTUyLCJleHAiOjE2OTU4MTczNTJ9.JSACi58i_9qxKssmGbWZtopqmyvcLwxtZ-0vaCj0Hfg

##################################################### PATIENT ############################################

### REGISTER
POST http://localhost:4000/patient/auth/register
Content-Type: application/json

{
  "email": "patient@testing.com",
  "password": "patienttest",
  "name": "patient test",
  "imageURL": "string"
}

### LOGIN FOR PATIENT

POST http://localhost:4000/patient/auth/login
Content-Type: application/json

{
  "email": "patient@testing.com",
  "password": "patienttest"
}

### GET ALL PATIENT
GET http://localhost:4000/patient

### GET BY ID
GET http://localhost:4000/patient/71458758-ba61-4e60-bc0c-8ccbec5adf7a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTQ1ODc1OC1iYTYxLTRlNjAtYmMwYy04Y2NiZWM1YWRmN2EiLCJuYW1lIjoicGF0aWVudCB0ZXN0IiwiZW1haWwiOiJwYXRpZW50MUB0ZXN0aW5nLmNvbSIsInJvbGUiOiJkb2N0b3IiLCJpYXQiOjE2OTU3MjM1OTEsImV4cCI6MTY5NTgwOTk5MX0.ek13DvbpswIEO1lbWqZvsEg7wcxm6rboCAbnrrMHlT0

### CHANGE PASSWORD

PATCH http://localhost:4000/patient/change-password/d88a1412-bef7-4e02-a654-d07c5e650861
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkODhhMTQxMi1iZWY3LTRlMDItYTY1NC1kMDdjNWU2NTA4NjEiLCJuYW1lIjoiaGVsbG8gbmV3IHBhdGllbnQiLCJlbWFpbCI6InBhdGllbnRAdGVzdGluZy5jb20iLCJyb2xlIjoiZG9jdG9yIiwiaWF0IjoxNjk1NzMwMTcyLCJleHAiOjE2OTU4MTY1NzJ9.Om_2p7tHnXJiTQOfbP7cHrNc4NQvNBvGzDUcSyjfb-Q
Content-Type: application/json

{
  "oldPassword": "newpatient",
  "newPassword": "patienttest"
}


################################# APPOINTMENT #################################

### CREATE APPOINTMENT
POST http://localhost:4000/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTk3NDhlMS1mZDEwLTRjMjAtOTRkMi05OWVlY2VkMjBkNzciLCJuYW1lIjoicGF0aWVudCB0ZXN0IiwiZW1haWwiOiJwYXRpZW50QHRlc3RpbmcuY29tIiwicm9sZSI6InBhdGllbnQiLCJpYXQiOjE2OTU3MzYzNDcsImV4cCI6MTY5NTgyMjc0N30.up4xPiXcsvPBq8V34RsoZg-WAlk0GcQ9IBvPnDom0YQ

{
  "patientID": "119748e1-fd10-4c20-94d2-99eeced20d77",
  "doctorID":"cba93c64-9d08-4d7e-967c-ea78db18903e",
  "datetime": "2023-09-20T10:43:19.187Z",
  "status": "Done"
}

### GET APPOINTMENT HISTORY USING DOCTOR'S TOKEN
GET http://localhost:4000/appointments/history/cba93c64-9d08-4d7e-967c-ea78db18903e?start=2023-9-01&end=2023-9-31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYmE5M2M2NC05ZDA4LTRkN2UtOTY3Yy1lYTc4ZGIxODkwM2UiLCJuYW1lIjoiYmFtYmFuZyIsImVtYWlsIjoidGVzdGluZ0BlbWFpbC5jb20iLCJyb2xlIjoiZG9jdG9yIiwiaWF0IjoxNjk1NzM3MTE3LCJleHAiOjE2OTU4MjM1MTd9.3jhqI2qNZxebWCTftvYG0KCceoIaM2Ja1hRRV0Y17ic

### GET APPOINTMENT HISTORY BY DOCTOR'S TOKEN
GET http://localhost:4000/appointments/history/5d1cceb3-1603-4a3a-97b7-5ba443647d48?start=2023-09-01&end=2023-09-30
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0ZDExYTQ0LWYwOGQtNDU1NS05ZGExLTU5MWJlMGI3NTU2ZCIsImVtYWlsIjoicGF0aWVudDFAdGVzdGluZy5jb20iLCJuYW1lIjoicGF0aWVudCB0ZXN0IiwiaW1hZ2VVUkwiOiJzdHJpbmciLCJpYXQiOjE2OTU1NDkxMzEsImV4cCI6MTY5NTYzNTUzMX0.opToQIVLzTVl7Pc42Qh_1rwzlCNs4aushrRQo5JPpZk